// User
export const USER_LOADING = "USER_LOADING";
export const NOT_LOADING = "NOT_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_FAIL = "USER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNING_IN = "SIGNING_IN";
export const LOGIN_OTP_SUCCESS = "LOGIN_OTP_SUCCESS";
export const LOGIN_OTP_QUESTION_SUCCESS = "LOGIN_OTP_QUESTION_SUCCESS";
export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const GET_All_NOTIFICATION = "GET_All_NOTIFICATION";
export const RESET_All_NOTIFICATION = "RESET_All_NOTIFICATION";

// Message
export const GET_MESSAGE = "GET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
// Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";

export const LOADING = "LOADING";

//Common Data
export const GET_All_CATEGORIES = "GET_All_CATEGORIES";
export const GET_MAIN_CATEGORIES = "GET_MAIN_CATEGORIES";
export const GET_TREE_CATEGORIES = "GET_TREE_CATEGORIES";
export const GET_JOBS = "GET_JOBS";
export const GET_FAVORITES_JOBS = "GET_FAVORITES_JOBS";
export const RESET_FAVORITES_JOBS = "RESET_FAVORITES_JOBS";
export const GET_NEWEST_JOBS = "GET_NEWEST_JOBS";
export const GET_FREELANCERS = "GET_FREELANCERS";
export const GET_NEWEST_FREELANCERS = "GET_NEWEST_FREELANCERS";
export const GET_FREELANCER = "GET_FREELANCER";
export const RESET_JOBS = "RESET_JOBS";
export const RESET_FREELANCERS = "RESET_FREELANCERS";
export const RESET_FREELANCER = "RESET_FREELANCER";
export const GET_PREVIOUS_SEARCH_VAlUE = "GET_PREVIOUS_SEARCH_VAlUE";
export const TIME_LINE_ITEMS = "TIME_LINE_ITEMS";
export const GET_PROPOSAL_LIST = "GET_PROPOSAL_LIST";

//Profile
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_FREELANCER_STATICS = "GET_FREELANCER_STATICS";
