export const languagesList = [
  {
    shortName: "sq",
    name: "Albanian",
    localName: "shqiptar",
    countries: ["Albania", "Kosovo", "North Macedonia"],
  },
  {
    shortName: "ar",
    name: "Arabic",
    localName: "العربية",
    countries: ["Egypt", "Sudan", "Algeria", "Iraq", "Morocco", "Saudi Arabia"],
  },
  {
    shortName: "bn",
    name: "Bengali",
    localName: "বাংলা",
    countries: ["Bangladesh", "India"],
  },
  {
    shortName: "ch",
    name: "Chinese",
    localName: "中文",
    countries: ["China", "Singapore", "Taiwan"],
  },
  {
    shortName: "nl",
    name: "Dutch",
    localName: "Nederlandse",
    countries: ["Netherlands", "Belgium", "Suriname"],
  },
  {
    shortName: "en",
    name: "English",
    localName: "English",
    countries: [
      "United Kingdom",
      "Nigeria",
      "Philippines",
      "Bangladesh",
      "India",
    ],
  },
  {
    shortName: "fr",
    name: "French",
    localName: "Français",
    countries: [
      "Canada",
      "Belgium",
      "Switzerland",
      "Madagascar",
      "Monaco",
      "Haiti",
    ],
  },
  {
    shortName: "de",
    name: "German",
    localName: "German",
    countries: [
      "Germany",
      "Austria",
      "Switzerland",
      "Belgium",
      "Luxembourg",
      "Liechtenstein",
    ],
  },
  {
    shortName: "gr",
    name: "Greek",
    localName: "ελληνική",
    countries: ["Greece", "Cyprus"],
  },
  {
    shortName: "gu",
    name: "Guarani",
    localName: "Avañe'ẽ",
    countries: ["Bolivia", "Paraguay"],
  },
  {
    shortName: "hi",
    name: "Hindi",
    localName: "हिंदुस्तानी",
    countries: [
      "India",
      "Fiji (known as Hindustani)",
      "Pakistan (known as Urdu)",
    ],
  },
  {
    shortName: "it",
    name: "Italian",
    localName: "Italiano",
    countries: ["Italy", "Switzerland", "San Marino", "Vatican City"],
  },
  {
    shortName: "ko",
    name: "Korean",
    localName: "한국어",
    countries: ["North Korea", "South Korea"],
  },
  {
    shortName: "ms",
    name: "Malay",
    localName: "Melayu",
    countries: [
      "Indonesia (known as Indonesian), Malaysia",
      "Singapore",
      "Brunei",
    ],
  },
  {
    shortName: "fa",
    name: "Persian",
    localName: "پارسی",
    countries: [
      "Iran",
      "Afghanistan (known as Dari), Tajikistan (known as Tajik)",
    ],
  },
  {
    shortName: "pt",
    name: "Portuguese",
    localName: "Português",
    countries: ["Portugal", "Brazil", "Mozambique", "Angola"],
  },
  {
    shortName: "ro",
    name: "Romanian",
    localName: "Română",
    countries: ["Romania", "Moldova"],
  },
  {
    shortName: "ru",
    name: "Russian",
    localName: "русский",
    countries: ["Russia", "Kazakhstan", "Belarus", "Kyrgyzstan"],
  },
  {
    shortName: "sr",
    name: "Serbo-Croatian",
    localName: "Српско-хрватски",
    countries: [
      "Serbia",
      "Croatia",
      "Bosnia and Herzegovina",
      "Montenegro",
      "Kosovo",
    ],
  },
  {
    shortName: "es",
    name: "Spanish",
    localName: "Español",
    countries: ["Spain", "Mexico", "Colombia", "Argentina"],
  },
  {
    shortName: "sw",
    name: "Swahili",
    localName: "Kiswahili",
    countries: [
      "Tanzania",
      "Kenya",
      "Uganda",
      "Rwanda",
      "Democratic Republic of the Congo",
    ],
  },
  {
    shortName: "sv",
    name: "Swedish",
    localName: "Swedish",
    countries: ["Sweden", "Finland"],
  },
  {
    shortName: "ta",
    name: "Tamil",
    localName: "தமிழ்",
    countries: ["Sri Lanka", "Singapore", "India"],
  },
  {
    shortName: "tr",
    name: "Turkish",
    localName: "Türk",
    countries: ["Turkey", "Cyprus"],
  },
];
